
.PHONY: all
all:
	gcc --std=c99 move_test.c ../../graphics/src/*.c ../src/controller.c ../src/cannon.c ../src/tank.c ../src/field.c ../src/led.c -I../include -I../../graphics/include -I../../sounds/include -o test
